2023-06-26 15:06:23,723 INFO    MainThread:1081804 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-26 15:06:23,723 INFO    MainThread:1081804 [wandb_setup.py:_flush():76] Configure stats pid to 1081804
2023-06-26 15:06:23,723 INFO    MainThread:1081804 [wandb_setup.py:_flush():76] Loading settings from /home/minkyoon/.config/wandb/settings
2023-06-26 15:06:23,723 INFO    MainThread:1081804 [wandb_setup.py:_flush():76] Loading settings from /home/minkyoon/crom/pyfile/relapse/mlp/mlpcsvpt/pyfile/wandb/settings
2023-06-26 15:06:23,723 INFO    MainThread:1081804 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-26 15:06:23,724 INFO    MainThread:1081804 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-26 15:06:23,724 INFO    MainThread:1081804 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'pyfile/relapse/mlp/mlpcsvpt/pyfile/backpro_batch_test_completecopy.py', 'program': '/home/minkyoon/crom/pyfile/relapse/mlp/mlpcsvpt/pyfile/backpro_batch_test_completecopy.py'}
2023-06-26 15:06:23,724 INFO    MainThread:1081804 [wandb_init.py:_log_setup():507] Logging user logs to /home/minkyoon/crom/pyfile/relapse/mlp/mlpcsvpt/pyfile/wandb/run-20230626_150617-v1ouwfaw/logs/debug.log
2023-06-26 15:06:23,724 INFO    MainThread:1081804 [wandb_init.py:_log_setup():508] Logging internal logs to /home/minkyoon/crom/pyfile/relapse/mlp/mlpcsvpt/pyfile/wandb/run-20230626_150617-v1ouwfaw/logs/debug-internal.log
2023-06-26 15:06:23,724 INFO    MainThread:1081804 [wandb_init.py:init():547] calling init triggers
2023-06-26 15:06:23,724 INFO    MainThread:1081804 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epoch': 100, 'batch': 2}
2023-06-26 15:06:23,724 INFO    MainThread:1081804 [wandb_init.py:init():596] starting backend
2023-06-26 15:06:23,724 INFO    MainThread:1081804 [wandb_init.py:init():600] setting up manager
2023-06-26 15:06:23,729 INFO    MainThread:1081804 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-06-26 15:06:24,253 INFO    MainThread:1081804 [wandb_init.py:init():606] backend started and connected
2023-06-26 15:06:24,262 INFO    MainThread:1081804 [wandb_init.py:init():703] updated telemetry
2023-06-26 15:06:28,247 INFO    MainThread:1081804 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-06-26 15:06:34,958 ERROR   MainThread:1081804 [wandb_init.py:init():762] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-06-26 15:06:35,093 ERROR   MainThread:1081804 [wandb_init.py:init():1170] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/minkyoon/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/home/minkyoon/anaconda3/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 768, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-06-26 15:06:36,176 WARNING MsgRouterThr:1081804 [router.py:message_loop():77] message_loop has been closed
